import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import Header from "./_components/Header";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GenForm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <SignedOut>
            <SignIn routing="hash" />
          </SignedOut> */}
          {/* <SignedIn> */}
            <Header />
            {children}
          {/* </SignedIn> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
